export type OnboardingFeature = "email" | "spreadsheets";

export type OnboardingStep = {
  id: string;
  title: string;
  path: string;
  description: string;
  tasks: string[];
  cta?: string;
  feature?: OnboardingFeature;
  selector?: string;
  selectorMobile?: string;
  placement?: "top" | "bottom" | "left" | "right" | "center";
  spotlightPadding?: number;
  requireTarget?: boolean;
};

export const ONBOARDING_STEPS: OnboardingStep[] = [
  {
    id: "dashboard-next-step",
    title: "Start from the next step card",
    path: "/app",
    description: "This card shows the next best action for your workspace.",
    tasks: [
      "Use this card when you want Louis to guide you instead of guessing where to click.",
      "The main button changes based on what your workspace still needs next.",
      "Start here whenever you come back and want the fastest next move.",
    ],
    cta: "Open Dashboard",
    selector: '[data-tour="dashboard-next-step"]',
    selectorMobile: '[data-tour="dashboard-next-step"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "dashboard-quick-actions",
    title: "Use quick actions to jump fast",
    path: "/app",
    description: "These shortcuts take you straight into the pages you will use most.",
    tasks: [
      "Use these when you already know what you want to do next.",
      "Chat, Docs, Bots, Schedule, Email, and Outreach should all be reachable from here.",
      "This section is for speed, not explanation.",
    ],
    cta: "Open Dashboard",
    selector: '[data-tour="dashboard-quick-actions"]',
    selectorMobile: '[data-tour="dashboard-quick-actions"]',
    placement: "top",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "bots-create",
    title: "Create a bot here",
    path: "/app/bots",
    description: "Bots give you separate knowledge workspaces inside Louis.",
    tasks: [
      "Create a bot when you want a separate assistant or knowledge area.",
      "Agency bots are shared. Private bots stay personal to their owner.",
      "This is usually your first setup step before uploading docs.",
    ],
    cta: "Open Bots",
    selector: '[data-tour="create-bot"]',
    selectorMobile: '[data-tour="create-bot"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "bots-list",
    title: "Review your existing bots",
    path: "/app/bots",
    description: "This area shows the bots already available in your workspace.",
    tasks: [
      "Use this list to switch between existing knowledge workspaces.",
      "If a bot already exists, you may not need to create another one.",
      "Keep bot names clean so the rest of the app stays easy to understand.",
    ],
    cta: "Open Bots",
    selector: '[data-tour="bots-list"]',
    selectorMobile: '[data-tour="bots-list"]',
    placement: "top",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "docs-bot-selector",
    title: "Choose which bot owns the docs",
    path: "/app/docs",
    description: "Documents are scoped to the selected bot.",
    tasks: [
      "Pick the bot before uploading so the right knowledge base gets the file.",
      "Agency bot docs are shared. Private bot docs stay private.",
      "If the wrong bot is selected, your answers will feel disconnected later.",
    ],
    cta: "Open Docs",
    selector: '[data-tour="docs-bot-selector"]',
    selectorMobile: '[data-tour="docs-bot-selector"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "docs-upload",
    title: "Upload your first document here",
    path: "/app/docs",
    description: "This is where you give Louis real knowledge.",
    tasks: [
      "Upload SOPs, onboarding docs, pricing, proposals, notes, or process docs here.",
      "Use this before asking internal questions in chat.",
      "The better your docs, the better Louis performs on internal work.",
    ],
    cta: "Open Docs",
    selector: '[data-tour="docs-upload"]',
    selectorMobile: '[data-tour="docs-upload"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "docs-actions",
    title: "Manage each document from here",
    path: "/app/docs",
    description: "Each document should have quick actions for cleanup and extraction.",
    tasks: [
      "Rename files so your workspace stays readable.",
      "Use extract when a document contains tasks, dates, or meetings.",
      "Delete outdated docs when they no longer belong in the bot’s knowledge.",
    ],
    cta: "Open Docs",
    selector: '[data-tour="docs-list"]',
    selectorMobile: '[data-tour="docs-list"]',
    placement: "top",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "chat-bot-selector",
    title: "Pick the bot before chatting",
    path: "/app/chat",
    description: "The selected bot controls which knowledge and behavior you are using.",
    tasks: [
      "Choose the bot that matches the work you want done.",
      "If the wrong bot is selected, answers may use the wrong docs.",
      "Always check this first when chat feels off.",
    ],
    cta: "Open Chat",
    selector: '[data-tour="chat-bot-selector"]',
    selectorMobile: '[data-tour="chat-bot-selector"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "chat-input",
    title: "Type your prompt here",
    path: "/app/chat",
    description: "This is the main input for asking Louis to think, summarize, write, or help.",
    tasks: [
      "Ask simple first prompts like: Summarize what this bot knows.",
      "Use this for internal questions, writing help, extraction help, and follow-up reasoning.",
      "If you uploaded docs already, this is where the value shows up fast.",
    ],
    cta: "Open Chat",
    selector: '[data-tour="chat-input"]',
    selectorMobile: '[data-tour="chat-input"]',
    placement: "top",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "chat-send",
    title: "Send the message here",
    path: "/app/chat",
    description: "After your prompt is ready, use this button to send it.",
    tasks: [
      "Send after checking the bot and prompt are both correct.",
      "Use short direct prompts first if you want cleaner answers.",
      "This is the final step to start your first real interaction.",
    ],
    cta: "Open Chat",
    selector: '[data-tour="chat-send"]',
    selectorMobile: '[data-tour="chat-send"]',
    placement: "top",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "schedule-overview",
    title: "Review extracted tasks and events here",
    path: "/app/schedule",
    description: "This page becomes useful after docs are extracted into real schedule items.",
    tasks: [
      "Come here after extraction to confirm meetings and tasks were created correctly.",
      "Use this page as your daily view for time-sensitive work.",
      "If extraction results are missing, check Docs and Extractions next.",
    ],
    cta: "Open Schedule",
    selector: '[data-tour="schedule-overview"]',
    selectorMobile: '[data-tour="schedule-overview"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "notifications-list",
    title: "Watch reminders here",
    path: "/app/notifications",
    description: "Notifications surface reminders, task updates, and schedule-related activity.",
    tasks: [
      "Use this page to stay ahead of deadlines and upcoming work.",
      "Check this when you want a quick list of what needs attention now.",
      "This should become part of your daily routine once the app is fully set up.",
    ],
    cta: "Open Notifications",
    selector: '[data-tour="notifications-list"]',
    selectorMobile: '[data-tour="notifications-list"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "extractions-history",
    title: "Review extraction history here",
    path: "/app/extractions",
    description: "This page shows what Louis pulled from uploaded documents.",
    tasks: [
      "Use this page to verify extraction results and history.",
      "Rename extraction runs so they stay easy to understand later.",
      "If a document produced bad results, this is where you check first.",
    ],
    cta: "Open Extractions",
    selector: '[data-tour="extractions-list"]',
    selectorMobile: '[data-tour="extractions-list"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "spreadsheets-main",
    title: "Generate sheets from here",
    path: "/app/spreadsheets",
    description: "This page is for structured spreadsheet workflows on supported plans.",
    tasks: [
      "Use this page when you want Louis to generate or edit spreadsheet-style data.",
      "Start with one clear action, not the whole page at once.",
      "If your plan includes it, this becomes a major workflow page.",
    ],
    cta: "Open Spreadsheets",
    feature: "spreadsheets",
    selector: '[data-tour="spreadsheets-main-action"]',
    selectorMobile: '[data-tour="spreadsheets-main-action"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "email-connect",
    title: "Connect and use email here",
    path: "/app/email",
    description: "This page handles inbox work, thread review, drafts, and sending on supported plans.",
    tasks: [
      "Connect Gmail here if it is not connected yet.",
      "After connection, use this page to review threads and draft replies.",
      "This should feel like your email workspace inside Louis.",
    ],
    cta: "Open Email",
    feature: "email",
    selector: '[data-tour="email-main-action"]',
    selectorMobile: '[data-tour="email-main-action"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "billing-plan",
    title: "Manage upgrades here",
    path: "/app/billing",
    description: "Billing controls plan access and feature unlocks.",
    tasks: [
      "Use this page to check your current plan and feature access.",
      "Upgrade here when you need more users, bots, or premium tools.",
      "This is also where you verify what your workspace should be able to use.",
    ],
    cta: "Open Billing",
    selector: '[data-tour="billing-main"]',
    selectorMobile: '[data-tour="billing-main"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "settings-main",
    title: "Adjust workspace settings here",
    path: "/app/settings",
    description: "Settings is where account and workspace preferences should live.",
    tasks: [
      "Use this page when you need to adjust account or workspace behavior.",
      "Treat this as your configuration page, not a daily workflow page.",
      "Return here when you want to change how the workspace behaves.",
    ],
    cta: "Open Settings",
    selector: '[data-tour="settings-main"]',
    selectorMobile: '[data-tour="settings-main"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "support-main",
    title: "Use support when something is wrong",
    path: "/app/support",
    description: "Support is the fallback when something breaks or blocks work.",
    tasks: [
      "Open support when you hit a product, billing, or account issue.",
      "Use clear titles so issues stay organized.",
      "This is the place to go when normal workflow stops working.",
    ],
    cta: "Open Support",
    selector: '[data-tour="support-main"]',
    selectorMobile: '[data-tour="support-main"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
];