export type OnboardingFeature = "email" | "spreadsheets";

export type OnboardingStep = {
  id: string;
  title: string;
  path: string;
  description: string;
  tasks: string[];
  cta?: string;
  feature?: OnboardingFeature;
};

export const ONBOARDING_STEPS: OnboardingStep[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    path: "/app",
    description:
      "This is your workspace home. It gives you a quick entry point into the rest of Louis.Ai.",
    tasks: [
      "Use this page as your starting point when you sign in.",
      "From here, move into chat, docs, schedule, and other tools.",
      "Think of this as the control center for your agency workspace.",
    ],
    cta: "Go to Dashboard",
  },
  {
    id: "chat",
    title: "Chat",
    path: "/app/chat",
    description:
      "This is your main AI workspace. Pick a bot, ask questions, summarize documents, and use the assistant for agency knowledge or general reasoning.",
    tasks: [
      "Open chat and confirm which bot is selected.",
      "Ask a simple question like: Summarize what this bot knows.",
      "Use chat for internal questions, writing, reasoning, and follow-up work.",
    ],
    cta: "Go to Chat",
  },
  {
    id: "docs",
    title: "Docs",
    path: "/app/docs",
    description:
      "Upload, rename, organize, and delete bot-scoped documents here. These files power your bot’s knowledge.",
    tasks: [
      "Upload your first internal document.",
      "Rename a document so your knowledge base stays clean.",
      "Use extraction if the document contains meetings, dates, or tasks.",
    ],
    cta: "Go to Docs",
  },
  {
    id: "bots",
    title: "Bots",
    path: "/app/bots",
    description:
      "Create and manage bots here. Agency bots are shared across the agency. Private bots stay personal to their owner.",
    tasks: [
      "Review the bots available in your workspace.",
      "Create a new bot if you want a separate knowledge workspace.",
      "Use Repair Vector Store only if a bot has indexing issues.",
    ],
    cta: "Go to Bots",
  },
  {
    id: "schedule",
    title: "Schedule",
    path: "/app/schedule",
    description:
      "This is where extracted meetings, reminders, and tasks appear after AI extraction.",
    tasks: [
      "Review extracted events and tasks.",
      "Check your to-do list.",
      "Use this page after extracting documents to confirm results.",
    ],
    cta: "Go to Schedule",
  },
  {
    id: "notifications",
    title: "Notifications",
    path: "/app/notifications",
    description:
      "This page shows reminders and schedule-related notifications generated by the system.",
    tasks: [
      "Review upcoming reminders.",
      "Check recent schedule or task notifications.",
      "Use this page daily to stay ahead of events and deadlines.",
    ],
    cta: "Go to Notifications",
  },
  {
    id: "extractions",
    title: "Extractions",
    path: "/app/extractions",
    description:
      "This page shows extraction history so you can track what was pulled from uploaded documents.",
    tasks: [
      "Review extraction runs.",
      "Rename runs to keep history understandable.",
      "Delete outdated or bad extraction runs if needed.",
    ],
    cta: "Go to Extractions",
  },
  {
    id: "spreadsheets",
    title: "Spreadsheets",
    path: "/app/spreadsheets",
    description:
      "This is where spreadsheet AI features live for supported paid plans.",
    tasks: [
      "Open this page if your plan includes spreadsheet features.",
      "Use it to work with structured data and AI-assisted spreadsheet workflows.",
      "Skip this for now if your plan does not include spreadsheet access.",
    ],
    cta: "Go to Spreadsheets",
    feature: "spreadsheets",
  },
  {
    id: "email",
    title: "Email",
    path: "/app/email",
    description:
      "Corporation tier users can connect Gmail here to summarize threads, draft replies, and manage inbox work.",
    tasks: [
      "Connect Gmail if your plan supports it.",
      "Open a thread and test summarization.",
      "Use email tools only after your Google OAuth setup is ready.",
    ],
    cta: "Go to Email",
    feature: "email",
  },
  {
    id: "billing",
    title: "Billing",
    path: "/app/billing",
    description:
      "Manage plan upgrades, subscription state, and premium feature access here.",
    tasks: [
      "Review your current plan.",
      "Check what features are locked or unlocked.",
      "Upgrade here when you need more users, bots, or premium tools.",
    ],
    cta: "Go to Billing",
  },
  {
    id: "settings",
    title: "Settings",
    path: "/app/settings",
    description:
      "Manage account and workspace settings here.",
    tasks: [
      "Review account-related settings.",
      "Check workspace-related preferences.",
      "Use this page for future account and profile adjustments.",
    ],
    cta: "Go to Settings",
  },
  {
    id: "support",
    title: "Support",
    path: "/app/support",
    description:
      "Use support when something breaks, a user is blocked, or you need billing or product help.",
    tasks: [
      "Open support if you hit a product or billing issue.",
      "Use clear issue titles so requests stay organized.",
      "Treat this as your fallback when something feels wrong.",
    ],
    cta: "Go to Support",
  },
];