export type OnboardingFeature = "email" | "spreadsheets";

export type OnboardingStep = {
  id: string;
  title: string;
  path: string;
  description: string;
  tasks: string[];
  cta?: string;
  feature?: OnboardingFeature;
  selector?: string;
  selectorMobile?: string;
  placement?: "top" | "bottom" | "left" | "right" | "center";
  spotlightPadding?: number;
  requireTarget?: boolean;
};

export const ONBOARDING_STEPS: OnboardingStep[] = [
  {
    id: "dashboard-next-step",
    title: "Start here",
    path: "/app",
    description: "This card shows the best next move for your workspace.",
    tasks: [
      "Use this when you want Louis to guide you step by step.",
      "The main button changes based on what your workspace still needs next.",
      "Come back here anytime you want the fastest next action.",
    ],
    cta: "Open Dashboard",
    selector: '[data-tour="dashboard-next-step"]',
    selectorMobile: '[data-tour="dashboard-next-step"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "dashboard-quick-actions",
    title: "Jump into the main pages fast",
    path: "/app",
    description: "These shortcuts take you straight to the core workflows.",
    tasks: [
      "Use these when you already know what you want to do next.",
      "This section is for speed, not explanation.",
      "It should help you move without hunting through the app.",
    ],
    cta: "Open Dashboard",
    selector: '[data-tour="dashboard-quick-actions"]',
    selectorMobile: '[data-tour="dashboard-quick-actions"]',
    placement: "top",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "bots-create",
    title: "Create a bot here",
    path: "/app/bots",
    description: "Bots give you separate workspaces inside Louis.",
    tasks: [
      "Create a bot when you want a separate assistant or knowledge area.",
      "Agency bots are shared. Private bots stay personal.",
      "This is usually the first setup step before uploading docs.",
    ],
    cta: "Open Bots",
    selector: '[data-tour="create-bot"]',
    selectorMobile: '[data-tour="create-bot"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "bots-list",
    title: "Review your existing bots",
    path: "/app/bots",
    description: "This area shows the bots already available in your workspace.",
    tasks: [
      "Use this list to switch between existing workspaces.",
      "If a bot already exists, you may not need to create another one.",
      "Keep bot names clear so the rest of the app stays easy to understand.",
    ],
    cta: "Open Bots",
    selector: '[data-tour="bots-list"]',
    selectorMobile: '[data-tour="bots-list"]',
    placement: "top",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "docs-bot-selector",
    title: "Choose which bot owns the docs",
    path: "/app/docs",
    description: "Documents are scoped to the selected bot.",
    tasks: [
      "Pick the bot before uploading so the right knowledge base gets the file.",
      "Agency bot docs are shared. Private bot docs stay private.",
      "If the wrong bot is selected, answers will feel disconnected later.",
    ],
    cta: "Open Docs",
    selector: '[data-tour="docs-bot-selector"]',
    selectorMobile: '[data-tour="docs-bot-selector"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "docs-upload",
    title: "Upload your first document here",
    path: "/app/docs",
    description: "This is where you give Louis real knowledge.",
    tasks: [
      "Upload SOPs, pricing, onboarding docs, notes, proposals, or process docs here.",
      "Use this before asking internal questions in chat.",
      "Louis should use uploaded docs and route useful information where it belongs.",
    ],
    cta: "Open Docs",
    selector: '[data-tour="docs-upload"]',
    selectorMobile: '[data-tour="docs-upload"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "docs-actions",
    title: "Manage your documents here",
    path: "/app/docs",
    description: "This area is where you keep uploaded knowledge clean and useful.",
    tasks: [
      "Rename files so your workspace stays readable.",
      "Delete outdated docs when they no longer belong in the bot’s knowledge.",
      "You should not need a separate extraction workflow to get value from uploads.",
    ],
    cta: "Open Docs",
    selector: '[data-tour="docs-list"]',
    selectorMobile: '[data-tour="docs-list"]',
    placement: "top",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "chat-bot-selector",
    title: "Pick the bot before chatting",
    path: "/app/chat",
    description: "The selected bot controls which knowledge and behavior you are using.",
    tasks: [
      "Choose the bot that matches the work you want done.",
      "If the wrong bot is selected, answers may use the wrong docs.",
      "Always check this first when chat feels off.",
    ],
    cta: "Open Chat",
    selector: '[data-tour="chat-bot-selector"]',
    selectorMobile: '[data-tour="chat-bot-selector"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "chat-input",
    title: "Type your prompt here",
    path: "/app/chat",
    description: "This is the main input for asking Louis to think, summarize, write, or help.",
    tasks: [
      "Ask simple first prompts like: Summarize what this bot knows.",
      "Use this for internal questions, writing help, and follow-up reasoning.",
      "If you uploaded docs already, this is where the value shows up fast.",
    ],
    cta: "Open Chat",
    selector: '[data-tour="chat-input"]',
    selectorMobile: '[data-tour="chat-input"]',
    placement: "top",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "chat-send",
    title: "Send the message here",
    path: "/app/chat",
    description: "After your prompt is ready, use this button to send it.",
    tasks: [
      "Send after checking the bot and prompt are both correct.",
      "Use short direct prompts first if you want cleaner answers.",
      "This is the final step to start your first real interaction.",
    ],
    cta: "Open Chat",
    selector: '[data-tour="chat-send"]',
    selectorMobile: '[data-tour="chat-send"]',
    placement: "top",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "schedule-bot-selector",
    title: "Choose which bot you are viewing",
    path: "/app/schedule",
    description: "The selected bot controls which tasks and events you are looking at.",
    tasks: [
      "Pick one bot to focus on that workspace only, or choose All bots for a combined view.",
      "Use this first when the schedule looks wrong or incomplete.",
      "This keeps shared agency schedules and private work separated correctly.",
    ],
    cta: "Open Schedule",
    selector: '[data-tour="schedule-bot-selector"]',
    selectorMobile: '[data-tour="schedule-bot-selector"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "schedule-view-switch",
    title: "Switch the schedule view here",
    path: "/app/schedule",
    description: "This control changes how much of your schedule you see at once.",
    tasks: [
      "Use Day when you want focus.",
      "Use Week when you want a working overview.",
      "Use Month when you want to scan for timing and density.",
    ],
    cta: "Open Schedule",
    selector: '[data-tour="schedule-view-switch"]',
    selectorMobile: '[data-tour="schedule-view-switch"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "schedule-events-list",
    title: "Review events here",
    path: "/app/schedule",
    description: "This is where schedule items become visible in calendar form.",
    tasks: [
      "Use this area to confirm meetings and event timing look right.",
      "Uploads should feed this automatically when Louis is confident.",
      "If something is unclear, Louis should ask instead of silently guessing.",
    ],
    cta: "Open Schedule",
    selector: '[data-tour="schedule-events-list"]',
    selectorMobile: '[data-tour="schedule-events-list"]',
    placement: "top",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "schedule-tasks-list",
    title: "Work from the daily task list here",
    path: "/app/schedule",
    description: "This side panel turns detected work into a practical day-by-day to-do list.",
    tasks: [
      "Use this for what needs attention today.",
      "Toggle tasks done as work gets completed.",
      "This should become one of the fastest daily workflow areas in the app.",
    ],
    cta: "Open Schedule",
    selector: '[data-tour="schedule-tasks-list"]',
    selectorMobile: '[data-tour="schedule-tasks-list"]',
    placement: "left",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "schedule-quick-add",
    title: "Add manual tasks or events here",
    path: "/app/schedule",
    description: "You can still add schedule items manually whenever you need to move fast.",
    tasks: [
      "Use this when you want to add something quickly yourself.",
      "Switch between event and task depending on what you are adding.",
      "This keeps schedule useful even before everything is perfectly automated.",
    ],
    cta: "Open Schedule",
    selector: '[data-tour="schedule-quick-add"]',
    selectorMobile: '[data-tour="schedule-quick-add"]',
    placement: "left",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "notifications-list",
    title: "Use this page as your reminder center",
    path: "/app/notifications",
    description: "This page pulls together the most important things that need your attention.",
    tasks: [
      "Check here for a quick read on what is coming up next.",
      "Use this as a daily scan page once tasks and events are flowing in.",
      "This page should help you notice work, not hunt for it.",
    ],
    cta: "Open Notifications",
    selector: '[data-tour="notifications-list"]',
    selectorMobile: '[data-tour="notifications-list"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "spreadsheets-main",
    title: "Generate sheets from here",
    path: "/app/spreadsheets",
    description: "This page is for structured spreadsheet workflows on supported plans.",
    tasks: [
      "Use this page when you want Louis to generate or edit spreadsheet-style data.",
      "Start with one clear action, not the whole page at once.",
      "If your plan includes it, this becomes a major workflow page.",
    ],
    cta: "Open Spreadsheets",
    feature: "spreadsheets",
    selector: '[data-tour="spreadsheets-main-action"]',
    selectorMobile: '[data-tour="spreadsheets-main-action"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "email-connect",
    title: "Connect and use email here",
    path: "/app/email",
    description: "This page handles inbox work, thread review, drafts, and sending on supported plans.",
    tasks: [
      "Connect Gmail here if it is not connected yet.",
      "After connection, use this page to review threads and draft replies.",
      "This should feel like your email workspace inside Louis.",
    ],
    cta: "Open Email",
    feature: "email",
    selector: '[data-tour="email-main-action"]',
    selectorMobile: '[data-tour="email-main-action"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "billing-plan",
    title: "Manage upgrades here",
    path: "/app/billing",
    description: "Billing controls plan access and feature unlocks.",
    tasks: [
      "Use this page to check your current plan and feature access.",
      "Upgrade here when you need more users, bots, or premium tools.",
      "This is also where you verify what your workspace should be able to use.",
    ],
    cta: "Open Billing",
    selector: '[data-tour="billing-main"]',
    selectorMobile: '[data-tour="billing-main"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "settings-main",
    title: "Adjust workspace settings here",
    path: "/app/settings",
    description: "Settings is where account and workspace preferences live.",
    tasks: [
      "Use this page when you need to adjust account or workspace behavior.",
      "Treat this as your configuration page, not a daily workflow page.",
      "Use restart onboarding here whenever you want the current guided tour again.",
    ],
    cta: "Open Settings",
    selector: '[data-tour="settings-main"]',
    selectorMobile: '[data-tour="settings-main"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
  {
    id: "support-main",
    title: "Use support when something is wrong",
    path: "/app/support",
    description: "Support is the fallback when something breaks or blocks work.",
    tasks: [
      "Open support when you hit a product, billing, or account issue.",
      "Use clear titles so issues stay organized.",
      "This is the place to go when normal workflow stops working.",
    ],
    cta: "Open Support",
    selector: '[data-tour="support-main"]',
    selectorMobile: '[data-tour="support-main"]',
    placement: "bottom",
    spotlightPadding: 10,
    requireTarget: true,
  },
];